name: Deploy to server

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH
        run: sudo apt-get update && sudo apt-get install -y openssh-client
        
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.ADMIN }}

      - name: SSH and deploy
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "
            cd ~/portfolio || exit
            git reset --hard origin/main
            git pull origin main
            ./deploy.sh || echo 'Deploy script not found'
          "
